// Generated by BUCKLESCRIPT VERSION 1.9.1, PLEASE EDIT WITH CARE
'use strict';

var Jest        = require("bs-jest/lib/js/src/jest.js");
var Header      = require("./header.js");
var Enzyme      = require("enzyme");
var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");

Jest.test("addition", (function () {
        return Jest.Expect[/* toBe */1](7)(Jest.Expect[/* expect */0](7));
      }));

describe("Header component", (function () {
        return Jest.test("renders children", (function () {
                      var expectedNode = "Test Header";
                      var wrapper = Enzyme.shallow(ReasonReact.element(/* None */0, /* None */0, Header.make(/* array */[expectedNode])));
                      return Jest.Expect[/* toBe */1](/* true */1)(Jest.Expect[/* expect */0](+wrapper.contains(expectedNode)));
                    }));
      }));

/*  Not a pure module */
