// Generated by BUCKLESCRIPT VERSION 1.9.1, PLEASE EDIT WITH CARE
'use strict';

var Jest    = require("bs-jest/lib/js/src/jest.js");
var Reducer = require("./reducer.js");

describe("reducer", (function () {
        Jest.test("returns initial state when state is undefined", (function () {
                var stories = /* array */[];
                var action = {
                  type: "SOME_ACTION",
                  payload: {
                    stories: stories
                  }
                };
                var state = Reducer.reducer(undefined, action);
                return Jest.Expect[/* toEqual */11]({
                              stories: stories
                            })(Jest.Expect[/* expect */0](state));
              }));
        Jest.test("returns current state if action unrecognised", (function () {
                var stories = /* array */[];
                var action = {
                  type: "SOME_ACTION",
                  payload: {
                    stories: stories
                  }
                };
                var state = Reducer.reducer(undefined, action);
                return Jest.Expect[/* toEqual */11](Reducer.initialState)(Jest.Expect[/* expect */0](state));
              }));
        return Jest.test("adds stories to state on RECEIVE_TOP_STORIES", (function () {
                      var stories = /* array */[
                        /* record */[
                          /* id */1,
                          /* title */"",
                          /* url */""
                        ],
                        /* record */[
                          /* id */2,
                          /* title */"",
                          /* url */""
                        ]
                      ];
                      var action = {
                        type: "RECEIVE_TOP_STORIES",
                        payload: {
                          stories: stories
                        }
                      };
                      var state = Reducer.reducer(Reducer.initialState, action);
                      return Jest.Expect[/* toEqual */11]({
                                    stories: stories
                                  })(Jest.Expect[/* expect */0](state));
                    }));
      }));

/*  Not a pure module */
