// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var Actions_re = require("./actions_re.js");

var initialState = {
  stories: /* array */[],
  loaded: false
};

function reducer(state, action) {
  var actionType = Actions_re.decodeActionType(action.type);
  if (state == null) {
    return initialState;
  } else if (typeof actionType === "number") {
    if (actionType !== 0) {
      return {
              stories: /* array */[],
              loaded: false
            };
    } else {
      return {
              stories: action.payload.stories,
              loaded: true
            };
    }
  } else {
    return state;
  }
}

var $$default = reducer;

exports.initialState = initialState;
exports.reducer      = reducer;
exports.$$default    = $$default;
exports.default      = $$default;
exports.__esModule   = true;
/* initialState Not a pure module */
