// Generated by BUCKLESCRIPT VERSION 1.9.1, PLEASE EDIT WITH CARE
'use strict';


var initialState = {
  stories: /* array */[]
};

function reducer(state, action) {
  if (state == null) {
    return initialState;
  } else {
    var match = action.type;
    if (match === "RECEIVE_TOP_STORIES") {
      return {
              stories: action.payload.stories
            };
    } else {
      return state;
    }
  }
}

var $$default = reducer;

exports.initialState = initialState;
exports.reducer      = reducer;
exports.$$default    = $$default;
exports.default      = $$default;
/* No side effect */
